name: Release

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  bake:
    environment:
      name: release

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Print definition
      env:
        BUILDX_GIT_LABELS: full
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
      run: docker buildx bake --print

    - name: Bake container images
      env:
        BUILDX_GIT_LABELS: full
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
      run: docker buildx bake --push
